#!/bin/bash

_repolink () {

    local regex

    regex='(https?)://github.com/.+/.+'

    if [[ $Tornadoes_REPO == "TornadoBot" ]]

    then

        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1FaXZhL0VpdmEtVXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d

    elif [[ $Tornadoes_REPO == "Tornadobot" ]]

    then

        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1FaXZhL0VpdmEtVXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d

    elif [[ $Tornadoes_REPO =~ $regex ]]

    then

        if [[ $Tornadoes_REPO_BRANCH ]]

        then

            echo "${Tornadoes_REPO}/archive/${Tornado_REPO_BRANCH}.zip"

        else

            echo "${Tornadoes_REPO}/archive/master.zip"

        fi

    else

        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1FaXZhL0VpdmEtVXNlcmJvdC9hcmNoaXZlL21haW4uemlw" | base64 -d

    fi

}

start_bot () {

    local zippath

    zippath="myTornadobot.zip"

    echo "  Downloading source code ..."

    wget -q $(_repolink) -O "$zippath"

    echo "  Unpacking Data ..."

    TornadoesPATH=$(zipinfo -1 "$zippath" | grep -v "/.");

    unzip -qq "$zippath"

    echo "  Processing Codes..."

    rm -rf "$zippath"

    sleep 5

    cd $EivaPATH

    echo "  • Starting TornadoBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt

    python3 -m Tornadobot

}

start_bot
